language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

sudo: false

install: composer install --no-interaction

script: composer test

addons:
  code_climate:
    repo_token: 78d27c9cf1bb57964da0d98f1e40b6aa92c9c7d06a7a4268a0b87d7d921c4123

after_success:
  - vendor/bin/test-reporter

  