language: php
dist: precise

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm-3.6

sudo: false

install: composer install --no-interaction

script: composer test

after_success:
  - vendor/bin/test-reporter

  
