language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

sudo: false

install: composer install --no-interaction

script: composer test

addons:
  code_climate:
    repo_token:
      secure: "Zh3sCkr1LizGn7cB3DVAVDeYCS4XQJ7sEgqbLyZFA+0YTKbT7kP0tIWx0juXF3Twps/wEIAz4Q7snK1aGzqkg53wcedbx27TSViSnmCMr7ViVrGPj9QMNzoB6xS5sG3LPbQ1Qa6osGL4IbFSiCkEuNYj9NGFYCAlT6qej1fnZ/c="

after_success:
  - vendor/bin/test-reporter

  
