language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

sudo: false

install: composer install --no-interaction

script: composer test

addons:
  code_climate:
    repo_token: 2c9de7918bc4d249e793a84d5767db500e404d79d2bc497ba13deb6a71989126

after_success:
  - vendor/bin/test-reporter

  